### ISSUE TITLE
Improve HTTPRateLimiter

### ISSUE THREAD

**Issue by mcuadros** [src-d/ghsync#11]
The current [HTTPRateLimiter](https://github.com/src-d/ghsync/blob/master/utils/rate.go) it's not working properly since is hitting the rate and returning errors, instead of wait until the query can be done.

BTW The current implementation is copy pasted from terraform-github 
https://github.com/terraform-providers/terraform-provider-github/commit/263b46a926ca0f1c5b458ac547c04e12b3b43377

**Comment by se7entyse7en** [comment]
@smacker I've started working on this again focusing on shallow sync.

I still have some doubts about the workflow that you explained:

```github.List() -> github.Do() -> (no error from limit yet) -> HTTPRateLimiter -> 
Real HTTP request -> Response

Response -> HTTPRateLimiter catches the error, goes to sleep and blocks everything
-> github.Do finishes only after sleep
-> github.List finishes only after sleep
-> github.List again
-> there is no limit because we were sleeping in block
```

Let's say that I start the shallow sync and that the quota is `N`, so:
```
github.Do() -> HTTPRateLimiter -> Real HTTP reqquest -> Response -> client sets remaining to N
github.Do() -> HTTPRateLimiter -> Real HTTP request -> Response -> client sets remaining to N - 1
...
github.Do() -> HTTPRateLimiter -> Real HTTP request -> Response -> client sets remaining to 1
github.Do() -> HTTPRateLimiter -> Real HTTP request -> Response -> client sets remaining to 0
github.Do() -> RateLimitError (real http request is skipped because client knows that remaining is 0 from last)
```
So for shallow sync it will simply exit, so it's not a big deal until we implement retry. In case of deep, the error makes the consumer take in charge the next item and when tyring request data for it, the client will raise the same `RateLimitError` and avoid doing the real http request. This will repeat again and again until all the items in the queue have been consumed.

If after reaching the limit, we restart the sync and the quota has not been reset yet, then the sleep occurs as the client doesn't have any information about how many remaining requests there are:
```
github.Do() -> client doesn't know that remaining is 0 -> HTTPRateLimiter -> Real HTTP request -> Response -> sleep
```

Initially, I thought that maybe when this was introduced this RT on `terraform-provider-github`, the client library doesn't perform any check, but [it doesn't seem the case](https://github.com/terraform-providers/terraform-provider-github/blob/v0.1.0/vendor/github.com/google/go-github/github/github.go#L401), at least it was already there since the very first release of `terraform-provider-github`. Maybe terraform has its own retry on error on top of their providers? So essentially what's happening is the same as restarting the process as I explained above, so sleep is actually working?

Does it make sense? Am I completely missing something?

**Comment by smacker** [comment]
> I still have some doubts about the workflow

please check the code HTTPRateLimiter. 
It checks response before returning anything: https://github.com/src-d/ghsync/blob/master/utils/rate.go#L66
The check return error when remaining = 0: https://github.com/google/go-github/blob/master/github/github.go#L748
And then goes to sleep as explained before.

So the last `github.Do()` won't be executed as long as limit wasn't reset.

> we implement retry

already implemented

> In case of deep

It is possible that this flow isn't going to work in deep, I didn't check the code in all the details. But we use goroutines there in some places which may cause problems.

**Comment by se7entyse7en** [comment]
But it [checks for status code first](https://github.com/google/go-github/blob/master/github/github.go#L737), isn't it?

**Comment by smacker** [comment]
Do you mean that GitHub would return status 200 and `headerRateRemaining = 0` in the same response?

I assumed it would return 403. But you are right, it's possible. (not sure if that really happens or not) In this case our limiter would be skipped. Can you test it? Just run shallow without `token` and log responses.

**Comment by se7entyse7en** [comment]
> Do you mean that GitHub would return status 200 and headerRateRemaining = 0 in the same response?

Exactly, here's an output taken from the console while I was debugging:

```
Doing request: &{GET https://api.github.com/repos/Viralize/shamash/pulls?per_page=100&state=all HTTP/1.1 1 1 map[Accept:[application/vnd.github.symmetra-preview+json, application/vnd.github.sailor-v-preview+json, application/vnd.github.shadow-cat-preview+json] User-Agent:[go-github]] <nil> <nil> 0 [] false api.github.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000a8008}
Request done. Resp: &{200 OK 200 HTTP/1.1 1 1 map[Access-Control-Allow-Origin:[*] Access-Control-Expose-Headers:[ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type] Cache-Control:[public, max-age=60, s-maxage=60] Content-Length:[2] Content-Security-Policy:[default-src 'none'] Content-Type:[application/json; charset=utf-8] Date:[Mon, 24 Jun 2019 16:44:11 GMT] Etag:["250ce138d4706285c4a567598eafec2a"] Referrer-Policy:[origin-when-cross-origin, strict-origin-when-cross-origin] Server:[GitHub.com] Status:[200 OK] Strict-Transport-Security:[max-age=31536000; includeSubdomains; preload] Vary:[Accept Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[deny] X-Github-Media-Type:[github.symmetra-preview; format=json, github.sailor-v-preview; format=json, github.shadow-cat-preview; format=json] X-Github-Request-Id:[DB2B:11326:3A72724:4970ADB:5D10FDDB] X-Ratelimit-Limit:[60] X-Ratelimit-Remaining:[0] X-Ratelimit-Reset:[1561398195] X-Xss-Protection:[1; mode=block]] 0xc000162180 2 [] false false map[] 0xc000140400 0xc00035a000}, Err: <nil>
```

**Comment by smacker** [comment]
I see. Thanks for debugging! Then I would proceed by changing the check inside HTTPRateLimiter. Instead of relying on go-github logic for errors it can just check that the header is present and the value of it is 0. And go to sleep. Because it is the only case limiter cares about.
