### ISSUE TITLE
docker-compose file is outdated

### ISSUE THREAD

**Issue by carlosms** [src-d/ghsync#43]
Docker-compose file uses rabbitmq, and uses the `sync` sub command that was renamed.

Since it's only useful to help with development, do we want to update it to work with `shallow` without rabbitmq, or can we drop it from this repo and just rely on the one from https://github.com/src-d/sourced-ce/blob/master/docker-compose.yml?

**Comment by se7entyse7en** [comment]
> can we drop it from this repo and just rely on the one from https://github.com/src-d/sourced-ce/blob/master/docker-compose.yml?

In order to consider this project as *standalone* I'd keep a `docker-compose.yml` file to easily run it. 

And since we didn't actually drop the `deep` sync, but we're not using it for timing constraints of our use case, it could make sense to also provide a `docker-compose.yml` file for `deep` import. Maybe having `docker-compose.yml` (or `docker-compose.shallow.yml`) and `docker-compose.deep.yml` makes sense?
